import net.fabricmc.loom.task.RemapJarTask
import net.fabricmc.loom.task.RemapSourcesJarTask

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'com.modrinth.minotaur' version '2.4.3' apply false
    id 'com.matthewprenger.cursegradle' version '1.4.0' apply false
}
if (System.getenv("MODRINTH_TOKEN")) {
    apply plugin: "com.modrinth.minotaur"
}
if (System.getenv("CURSEFORGE_TOKEN")) {
    apply plugin: "com.matthewprenger.cursegradle"
}

repositories {
    maven {
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    modCompileOnly("mezz.jei:${jei_version}") { transitive = false }
    modCompileOnly "com.terraformersmc:modmenu:6.1.0-rc.4"
}

loom {
    accessWidenerPath = project(':fabric').file("src/main/resources/emi.accesswidener")
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
loom.remapConfigurations.configureEach {
    configurations.named(it.name) {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}

def remapJar = tasks.named('remapJar', RemapJarTask)

def remapSourcesJar = tasks.named('remapSourcesJar', RemapSourcesJarTask)

def filteredSourcesJar = tasks.register('filteredSourcesJar', Jar, {
    archiveClassifier = 'filtered-sources'
    dependsOn remapSourcesJar
    from zipTree(remapSourcesJar.flatMap { it.archiveFile })
    exclude 'dev/emi/emi/jemi/**'
})

def apiJar = tasks.register('apiJar', Jar, {
    archiveClassifier = 'api'
    dependsOn remapJar
    from zipTree(remapJar.flatMap { it.archiveFile })
    include 'fabric.mod.json'
    include 'emi.mixins.json'
    include 'emi-fabric.mixins.json'
    include 'emi.accesswidener'
    include 'dev/emi/emi/api/**'
    exclude 'dev/emi/emi/api/EmiRecipeHandler**'
    exclude 'dev/emi/emi/api/stack/FluidEmiStack**'
    exclude 'dev/emi/emi/api/stack/ItemEmiStack**'
    exclude 'dev/emi/emi/api/stack/EmptyEmiStack**'
    exclude 'dev/emi/emi/api/stack/TagEmiIngredient**'
    exclude 'dev/emi/emi/api/stack/ListEmiIngredient**'
})

tasks.named("build").configure {
    dependsOn(filteredSourcesJar, apiJar)
}

publishing {
    publications {
        register('maven', MavenPublication) {
            artifactId = "${rootProject.name}-${project.name}"
            version = project.version
            artifact(remapJar) {
                classifier ''
            }
            artifact(filteredSourcesJar) {
                classifier 'sources'
            }
            artifact(apiJar) {
                classifier 'api'
            }
        }
    }
    setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
    if (project.hasProperty("mavenUrl")) {
        repositories.maven {
            url project.mavenUrl
            credentials {
                username project.mavenUsername
                password project.mavenPassword
            }
        }
    }
}

if (System.getenv("MODRINTH_TOKEN")) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = 'emi'
        versionNumber = project.version
        versionName = project.version
        versionType = 'release'
        uploadFile = remapJar
        gameVersions = [rootProject.minecraft_version]
        loaders = ['fabric', 'quilt']
        detectLoaders = false
        changelog = file('../CHANGELOG.md').text
    }
}

if (System.getenv("CURSEFORGE_TOKEN")) {
    curseforge {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = '580555'
            releaseType = 'release'
            changelogType = 'markdown'
            changelog = file('../CHANGELOG.md')

            addGameVersion rootProject.minecraft_version
            addGameVersion 'Fabric'
            addGameVersion 'Quilt'

            mainArtifact(remapJar.get().archiveFile) {
                displayName = 'emi-' + project.version
            }
        }
        options {
            javaIntegration = false
            forgeGradleIntegration = false
            javaVersionAutoDetect = false
        }
    }
}
