import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath 'com.modrinth.minotaur:Minotaur:2.4.3'
		classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
	}
}

plugins {
	id "dev.architectury.loom-no-remap"
	id "com.gradleup.shadow" version "9.4.1"
}
if (System.getenv("MODRINTH_TOKEN")) {
	apply plugin: "com.modrinth.minotaur"
}
if (System.getenv("CURSEFORGE_TOKEN")) {
	apply plugin: "com.matthewprenger.cursegradle"
}
evaluationDependsOn ':xplat'

architectury {
	platformSetupLoomIde()
	fabric()
}

loom {
	accessWidenerPath = project(":xplat").loom.accessWidenerPath

	mods {
		main {
			sourceSet sourceSets.main
			sourceSet project(':xplat').sourceSets.main
		}
	}
}

configurations {
	common
	shadowCommon
	compileClasspath.extendsFrom common
	runtimeClasspath.extendsFrom common
	developmentFabric.extendsFrom common
}

repositories {
	maven {
		url = "https://maven.terraformersmc.com/"
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
	api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

	common(project(path: ":xplat")) { transitive false }
	shadowCommon(project(path: ":xplat", configuration: "transformProductionFabric")) { transitive false }

	compileOnly("mezz.jei:${rootProject.jei_version}") {
		transitive = false
	}
	compileOnly "com.terraformersmc:modmenu:18.0.0-alpha.8"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

def shadowJar = tasks.named('shadowJar', ShadowJar)

shadowJar.configure { ShadowJar jar ->
	jar.exclude "architectury.common.json"

	jar.configurations = [project.configurations.shadowCommon]
	jar.archiveClassifier = ""
}

tasks.named('jar', Jar).configure {
	archiveClassifier = "dev"
}

tasks.named('sourcesJar', Jar).configure { Jar jar ->
	def commonSources = project(":xplat").tasks.named("sourcesJar", Jar)
	dependsOn commonSources
	jar.from zipTree(commonSources.get().archiveFile)
}

def filteredSourcesJar = tasks.register('filteredSourcesJar', Jar, {
	archiveClassifier = 'filtered-sources'
	dependsOn sourcesJar
	from zipTree(sourcesJar.archiveFile)
	exclude 'dev/emi/emi/jemi/**'
})

def apiJar = tasks.register('apiJar', Jar, {
	archiveClassifier = 'api'
	dependsOn shadowJar
	from zipTree(shadowJar.get().archiveFile)
	include 'LICENSE'
	include 'fabric.mod.json'
	include 'emi.mixins.json'
	include 'emi-fabric.mixins.json'
	include 'emi.accesswidener'
	include 'dev/emi/emi/api/**'
	exclude 'dev/emi/emi/api/EmiRecipeHandler**'
	exclude 'dev/emi/emi/api/stack/FluidEmiStack**'
	exclude 'dev/emi/emi/api/stack/ItemEmiStack**'
	exclude 'dev/emi/emi/api/stack/EmptyEmiStack**'
	exclude 'dev/emi/emi/api/stack/TagEmiIngredient**'
	exclude 'dev/emi/emi/api/stack/ListEmiIngredient**'
})

tasks.named("build").configure {
	dependsOn(filteredSourcesJar, apiJar)
}

components.java {
	withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
		skip()
	}
}

publishing {
	publications {
		register('maven', MavenPublication) {
			artifactId = "${rootProject.name}-${project.name}"
			version = project.ext.mavenVersion
			artifact(shadowJar) {
				builtBy shadowJar
				classifier ''
			}
			artifact(filteredSourcesJar) {
				builtBy filteredSourcesJar
				classifier 'sources'
			}
			artifact(apiJar) {
				builtBy apiJar
				classifier 'api'
			}
		}
	}
	setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
	if (project.hasProperty("mavenUrl")) {
		repositories.maven {
			url project.mavenUrl
			credentials {
				username project.mavenUsername
				password project.mavenPassword
			}
		}
	}
}

if (System.getenv("MODRINTH_TOKEN")) {
	modrinth {
		token = System.getenv("MODRINTH_TOKEN")
		projectId = 'emi'
		versionNumber = project.version
		versionName = project.version
		versionType = 'release'
		uploadFile = shadowJar
		gameVersions = [rootProject.minecraft_version]
		loaders = ['fabric', 'quilt']
		detectLoaders = false
		changelog = file('../CHANGELOG.md').text
	}
}

if (System.getenv("CURSEFORGE_TOKEN")) {
	curseforge {
		apiKey = System.getenv("CURSEFORGE_TOKEN")
		project {
			id = '580555'
			releaseType = 'release'
			changelogType = 'markdown'
			changelog = file('../CHANGELOG.md')

			addGameVersion rootProject.minecraft_version
			addGameVersion 'Fabric'
			addGameVersion 'Quilt'

			mainArtifact(shadowJar.get().archiveFile) {
				displayName = 'emi-' + project.version
			}
		}
		options {
			javaIntegration = false
			forgeGradleIntegration = false
			javaVersionAutoDetect = false
		}
	}
}
