apply plugin: "dev.architectury.loom-no-remap"

architectury {
	common(rootProject.enabled_platforms.split(","))
}

loom {
	accessWidenerPath = file("src/main/resources/emi.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

	compileOnly("mezz.jei:${rootProject.jei_version}") {
		transitive = false
	}
}

processResources {
	inputs.property "version", project(":fabric").version

	filesMatching("fabric.mod.json") {
		expand "version": project(":fabric").version
	}
}


def filteredSourcesJar = tasks.register('filteredSourcesJar', Jar, {
	archiveClassifier = 'filtered-sources'
	dependsOn sourcesJar
	from zipTree(sourcesJar.archiveFile)
	exclude 'dev/emi/emi/jemi/**'
})

def apiJar = tasks.register('apiJar', Jar, {
	archiveClassifier = "api"
	dependsOn jar
	from zipTree(jar.archiveFile)
	include 'fabric.mod.json'
	include 'emi.mixins.json'
	include 'emi.accesswidener'
	include 'dev/emi/emi/api/**'
	exclude 'dev/emi/emi/api/EmiRecipeHandler**'
	exclude 'dev/emi/emi/api/stack/FluidEmiStack**'
	exclude 'dev/emi/emi/api/stack/ItemEmiStack**'
	exclude 'dev/emi/emi/api/stack/EmptyEmiStack**'
	exclude 'dev/emi/emi/api/stack/TagEmiIngredient**'
	exclude 'dev/emi/emi/api/stack/ListEmiIngredient**'
})

tasks.named("build").configure {
	dependsOn(filteredSourcesJar, apiJar)
}

publishing {
	publications {
		register('maven', MavenPublication) {
			artifactId = "${rootProject.name}-xplat-mojmap"
			version = project.ext.mavenVersion
			artifact(jar) {
				builtBy jar
				classifier = null
			}
			artifact(filteredSourcesJar) {
				builtBy filteredSourcesJar
				classifier = 'sources'
			}
			artifact(apiJar) {
				builtBy apiJar
				classifier = 'api'
			}
		}
	}
	setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
	if (project.hasProperty("mavenUrl")) {
		repositories.maven {
			url project.mavenUrl
			credentials {
				username project.mavenUsername
				password project.mavenPassword
			}
		}
	}
}