org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.2-snapshot-6
enabled_platforms=fabric,neoforge

archives_base_name=emi
mod_version=1.1.22
maven_group=dev.emi

architectury_version=4.9.83

fabric_loader_version=0.19.2
fabric_api_version=0.148.2+26.2

forge_version=1.20.4-49.0.9

neoforge_version=26.1.2.48-beta

jei_version=jei-26.1.2-fabric:29.5.0.28
