plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'com.modrinth.minotaur' version '2.4.3' apply false
    id 'com.matthewprenger.cursegradle' version '1.4.0' apply false
}
if (System.getenv("MODRINTH_TOKEN")) {
    apply plugin: "com.modrinth.minotaur"
}
if (System.getenv("CURSEFORGE_TOKEN")) {
    apply plugin: "com.matthewprenger.cursegradle"
}

neoForge {
    version = neoforge_version
    def at = project(':xplat').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            clientData()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}

def filteredSourcesJar = tasks.register('filteredSourcesJar', Jar, {
    archiveClassifier = 'filtered-sources'
    def sourcesJar = tasks.named('sourcesJar', Jar)
    dependsOn sourcesJar
    from zipTree(sourcesJar.flatMap { it.archiveFile })
    exclude 'dev/emi/emi/jemi/**'
})

def apiJar = tasks.register('apiJar', Jar, {
    archiveClassifier = 'api'
    def jarTask = tasks.named('jar', Jar)
    dependsOn jarTask
    from zipTree(jarTask.flatMap { it.archiveFile })
    include 'emi.mixins.json'
    include 'emi-neoforge.mixins.json'
    include 'emi.accesswidener'
    include 'dev/emi/emi/api/**'
    exclude 'dev/emi/emi/api/EmiRecipeHandler**'
    exclude 'dev/emi/emi/api/stack/FluidEmiStack**'
    exclude 'dev/emi/emi/api/stack/ItemEmiStack**'
    exclude 'dev/emi/emi/api/stack/EmptyEmiStack**'
    exclude 'dev/emi/emi/api/stack/TagEmiIngredient**'
    exclude 'dev/emi/emi/api/stack/ListEmiIngredient**'
})

tasks.named("build").configure {
    dependsOn(filteredSourcesJar, apiJar)
}

publishing {
    publications {
        register('maven', MavenPublication) {
            artifactId = "${rootProject.name}-${project.name}"
            version = project.version
            artifact(tasks.named('jar'))
            artifact(filteredSourcesJar) {
                classifier = 'sources'
            }
            artifact(apiJar) {
                classifier = 'api'
            }
        }
    }
    setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
    if (project.hasProperty("mavenUrl")) {
        repositories.maven {
            url project.mavenUrl
            credentials {
                username project.mavenUsername
                password project.mavenPassword
            }
        }
    }
}

if (System.getenv("MODRINTH_TOKEN")) {
    modrinth {
        token = System.getenv("MODRINTH_TOKEN")
        projectId = 'emi'
        versionNumber = project.version
        versionName = project.version
        versionType = 'release'
        uploadFile = tasks.named('jar')
        gameVersions = [rootProject.minecraft_version]
        loaders = ['neoforge']
        detectLoaders = false
        changelog = file('../CHANGELOG.md').text
    }
}

if (System.getenv("CURSEFORGE_TOKEN")) {
    curseforge {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        project {
            id = '580555'
            releaseType = 'release'
            changelogType = 'markdown'
            changelog = file('../CHANGELOG.md')

            addGameVersion rootProject.minecraft_version
            addGameVersion 'NeoForge'

            mainArtifact(tasks.named('jar').get().archiveFile) {
                displayName = 'emi-' + project.version
            }
        }
        options {
            javaIntegration = false
            forgeGradleIntegration = false
            javaVersionAutoDetect = false
        }
    }
}
